### ISSUE TITLE
repeated printed logging info：Initializing global attention on question tokens...

### ISSUE THREAD

**Issue by xixiaoyao** [patil-suraj/Notebooks#2]
I run the notebook but when running on `main()` block, I find the following info are repeated printed with training steps.

![image](https://user-images.githubusercontent.com/24541791/93876145-e8788680-fd08-11ea-8b43-42b6ad94cfa7.png)

**Comment by patil-suraj** [comment]
Hi,could try calling this as the first line in `main`

```python
from transformers import logging as hf_logging
 hf_logging.set_verbosity_info()
```

that log is coming from the longformer model which sets gloabal attention on question token automatically

**Comment by xixiaoyao** [comment]
it works. Thanks!
