### ISSUE TITLE
Is token_type_ids necesssary for Longformer?

### ISSUE THREAD

**Issue by xixiaoyao** [patil-suraj/Notebooks#3]
I notice that the `token_type_ids` is not generated for model training, while this feature is widely used for BERT-like models. I wonder if the missing of `token_type_ids` could degrade model performance?

**Comment by patil-suraj** [comment]
Hey, @xixiaoyao , `token_typ_ids` are not necessary for `Longformer` so they are not created.

**Comment by xixiaoyao** [comment]
Thanks :-)
